apiVersion: v1
kind: Service
metadata:
  name: flohmarkt-web
  labels:
    app: flohmarkt-web
spec:
  ports:
    - port: 8000
      name: web
  clusterIP: None
  selector:
    app: flohmarkt-web

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flohmarkt-web
spec:
  serviceName: "flohmarkt-web"
  replicas: 1
  selector:
    matchLabels:
      app: flohmarkt-web
  template:
    metadata:
      annotations:
        k8up.io/backupcommand: tar -C /var/lib/flohmarkt/ -cf /dev/stdout - ./
        k8up.io/file-extension: .tar
      labels:
        app: flohmarkt-web
    spec:
      volumes:
        - name: flohmarkt-config
          secret:
            secretName: flohmarkt-config
      containers:
        - name: web
          image: codeberg.org/waaaaargh/flohmarkt:latest
          command: ["/entrypoint.sh", "web"]
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: web
          volumeMounts:
            - name: flohmarkt-data
              mountPath: /var/lib/flohmarkt
          envFrom:
            - configMapRef:
                name: flohmarkt-config
            - secretRef:
                name: flohmarkt-secrets
          env:
            - name: FLOHMARKT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: COUCHDB_PASSWORD

  volumeClaimTemplates:
    - metadata:
        name: flohmarkt-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
