apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mosquitto
  annotations:
    cert-manager.io/cluster-issuer: le-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - taler-exchange.lab.weltraumpflege.org
      secretName: ingress-cert
  rules:
    - host: taler-exchange.lab.weltraumpflege.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taler-exchange
                port:
                  number: 80
