apiVersion: v1
kind: Service
metadata:
  name: taler-exchange
  labels:
    app: taler-exchange
spec:
  ports:
    - port: 80
      name: websockets
  clusterIP: None
  selector:
    app: taler-exchange
