apiVersion: v1
kind: Service
metadata:
  name: mautrix-discord 
  labels:
    app: mautrix-discord
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: mautrix-discord

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mautrix-discord
spec:
  serviceName: mautrix-discord
  selector:
    matchLabels:
      app: mautrix-discord # has to match .spec.template.metadata.labels
  replicas: 1
  template:
    metadata:
      labels:
        app: mautrix-discord
    spec:
      containers:
      - name: mautrix-discord
        image: dock.mau.dev/mautrix/discord:a6d9e62b497a36c4b61d240d6dc774359be65168-arm64
        ports:
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "openebs-hostpath"
      resources:
        requests:
          storage: 1Gi
